### ISSUE TITLE
Develop cards UI

### ISSUE THREAD

**Issue by ImLuze** [tirette/main-website#4]
**Is your feature request related to a problem? Please describe.**
We need a way to make all recent news items and promotions clear to the user in a glimpse of an eye.

**Describe the solution you'd like**
Create a card UI for all the news items, updates, blog posts, promotions etc... This creates a very dynamic UI which can easily adapt to very different kinds of content and get the message across without losing the general look and feel of the website.

**Additional context**
- [x] Create a dynamic component which can handle any type of card in any order.
- [x] Add features card #8 
- [x] Add product card #9 
- [x] Add news card #10
